"""Verifies this port against ports/testvectors.json.

The vectors are generated by the Go implementation, which asserts each value
against captured ground truth before writing them.

    python tests/conformance.py
"""

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

import arkose_solver as A  # noqa: E402
from arkose_solver import derived as D  # noqa: E402

VECTORS = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "..", "testvectors.json")

with open(VECTORS, encoding="utf-8") as fh:
    v = json.load(fh)

passed = 0
failed = 0


def check(name, got, want):
    global passed, failed
    if got == want:
        passed += 1
    else:
        failed += 1
        print("FAIL %s\n  got  %r\n  want %r" % (name, got, want))


for t in v["khash"]:
    check("khash(seed=%d, len=%d)" % (t["seed"], len(t["input"])),
          A.khash(t["input"], t["seed"]), t["want"])

check("compute_f", A.compute_f(v["fe"]), v["wantF"])
check("compute_ife_hash", A.compute_ife_hash(v["fe"]), v["wantIfeHash"])

for w in v["webgl"]:
    fields = A.build_webgl_fields(w["vendor"], w["renderer"])
    from arkose_solver.webgl import webgl_hash_input
    check("%s hashInput" % w["name"], webgl_hash_input(fields), w["hashInput"])
    check("%s webgl_hash_webgl" % w["name"], A.compute_webgl_hash(fields), w["wantHash"])
    check("%s rtt_type" % w["name"],
          A.compute_rtt_type(v["webglExtensionsHash"], w["wantHash"]), w["wantRttType"])

d = v["derived"]
check("webgl_extensions_hash", A.compute_webgl_extensions_hash(d["webglExtensions"]),
      d["wantWebglExtensionsHash"])
check("f58835f", A.compute_f58835f(), d["wantF58835f"])
check("browser_object_checks", A.compute_browser_object_checks(["chrome"]),
      d["wantBrowserObjectChecks"])
check("29s83ih9", D.md5("false"), d["want29s83ih9"])

sv, sh = A.compute_speech(d["speechVoices"])
check("speech_default_voice", sv, d["wantSpeechDefaultVoice"])
check("speech_voices_hash", sh, d["wantSpeechVoicesHash"])
check("audio_codecs_extended_hash", A.audio_codecs_extended_hash(),
      d["wantAudioCodecsExtendedHash"])
check("video_codecs_extended_hash", A.video_codecs_extended_hash(),
      d["wantVideoCodecsExtendedHash"])

# A generated payload must be internally consistent, not just individually correct.
from arkose_solver.bda import generate_bda  # noqa: E402

for i in range(20):
    items = generate_bda({
        "surl": "https://verify.example.com",
        "window_location_href": "https://www.example.com/sign-in",
        "sitedata_location_href": "https://www.example.com/sign-in",
        "language": "en-US",
        "title": "Sign in",
    })
    top = {x["key"]: x["value"] for x in items}
    ef_list = top["enhanced_fp"]
    ef = {x["key"]: x["value"] for x in ef_list}

    check("bda[%d] enhanced_fp length" % i, len(ef_list), 91)
    check("bda[%d] f self-consistent" % i, top["f"], A.compute_f(top["fe"]))
    check("bda[%d] ife_hash self-consistent" % i, top["ife_hash"],
          A.compute_ife_hash(top["fe"]))

    idx = next(n for n, x in enumerate(ef_list) if x["key"] == "webgl_hash_webgl")
    check("bda[%d] webgl_hash index" % i, idx, 18)
    check("bda[%d] webgl_hash self-consistent" % i, ef["webgl_hash_webgl"],
          A.compute_webgl_hash([(x["key"], x["value"]) for x in ef_list[:idx]]))
    check("bda[%d] rtt_type tracks webgl hash" % i, ef["network_info_rtt_type"],
          A.compute_rtt_type(ef["webgl_extensions_hash"], ef["webgl_hash_webgl"]))

    color_depth = int(next(e for e in top["fe"] if e.startswith("D:"))[2:])
    check("bda[%d] screen_pixel_depth" % i, ef["screen_pixel_depth"], color_depth * 3)

print("%d passed, %d failed" % (passed, failed))
sys.exit(1 if failed else 0)
